### ISSUE TITLE
school blocking

### ISSUE THREAD

**Issue by easella** [sysce/proxy#6]
crap.
![image](https://user-images.githubusercontent.com/74786054/112698269-b4b91d80-8e5f-11eb-86a1-90444759c23d.png)
my schools also blocks https://phenix-le.cf , holyubofficial.net,grammarfiles.net,  referencefile.org, and holyubofficial.ml #

**Comment by easella** [comment]
can you please deploy this to heroku? When I deploy it to heroku the request times out(I think there is a syntax error or whatever.)

**Comment by Nickbutno** [comment]
why did you post your ip along with it

**Comment by easella** [comment]
because when you go to a blocked site contentkeeper records your ip.

**Comment by WeDoABitOfTrolling** [comment]
you could have just censored it lol
