### ISSUE TITLE
please provide a heroku demo

### ISSUE THREAD

**Issue by easella** [sysce/proxy#7]
when I deploy it to heroku it does not even load. it also says there is an application error.
![image](https://user-images.githubusercontent.com/74786054/113228560-21b72380-9263-11eb-8f21-e623965e0204.png)

**Comment by e9x** [comment]
I will get to fixing this soon.

**Comment by easella** [comment]
please fix it! i wannt play krunker and wings io!

**Comment by e9x** [comment]
Please be patient!

**Comment by Zediku** [comment]
yea i have the same problem here

**Comment by easella** [comment]
please fix it now!

**Comment by Pers0n-dev** [comment]
@easella a bypass is nice... What you have to do is open the Zoom extension (assuming you are not currently in a meeting), and then click “Sign In,” and then “Sign in with Google.” You will then need to click where it leads you to “Create Account.” From there, click “Sign in instead.” Then click the blue text that reads “Learn More.” Now you should be in the Google Chrome Help center, but still in the Zoom extension. Click the three horizontal lines in the top left corner, then go to the “Privacy Policy” page. Finally, scroll all the way to the very bottom of that page and click the tiny link in the bottom left corner that reads “Google.”

That’s all! Search anything you want and have fun playing any game, chatting with friends, or browsing any social media website. This should work on any school chromebook, but unfortunately it will not work on school wifi if you happen to be on campus. But if you are at home and your parents have not enabled any filters on the wifi, this will work.

**Comment by e9x** [comment]
I fail to see how using a bypass is relevant to the development of a proxy script.

**Comment by Pers0n-dev** [comment]
idk

**Comment by easella** [comment]
I already knew about those proxies. Most of them are blocked. Can you provide me with anymore?

**Comment by easella** [comment]
also I need systemya to be deployed to heroku because by schools blocks all the links that you already have up and this proxy does not work well on repl.co(styling is almost always lost and games that I know work with system ya appear blank when I use it in repl.co)

**Comment by easella** [comment]
there is no learn button and I signed in with google like you told me to.

**Comment by easella** [comment]
it does not work.

**Comment by easella** [comment]
![image](https://user-images.githubusercontent.com/74786054/114778591-0c51f700-9d43-11eb-8d68-381bbb52aa28.png)

**Comment by e9x** [comment]
Please consider censoring personal information in your screenshsot

**Comment by Pers0n-dev** [comment]
like this
![screenshot](https://user-images.githubusercontent.com/81875430/114791851-0b699700-9d3c-11eb-8d8c-8bf5f9283a4d.png)

**Comment by easella** [comment]
ok sure

**Comment by easella** [comment]
and zoom does not worK by the way

**Comment by Pers0n-dev** [comment]
DELETE YOUR FIRST PIC

**Comment by easella** [comment]
thank you

**Comment by easella** [comment]
hey guys try my unblocked games site:[click here](https://games.awdrgyjil1234.repl.co/l)
